In [1]:
import pandas as pd

In [2]:
import pandas as pd

df = pd.read_csv("Datasets/AsphaltPavementType_combine.csv")
df2 = pd.read_csv("Datasets/AsphaltPavementType_TEST.csv")

subsetA = df.iloc[1055:]

# pastikan kolom yang dibandingkan sama
common_cols = df2.columns.intersection(subsetA.columns).tolist()

# buang duplikat supaya set lebih kecil
subsetA_unique = subsetA[common_cols].drop_duplicates()

# bikin "kunci" per baris (string) agar mudah dicek
keyA = subsetA_unique.astype(str).agg("|".join, axis=1)

key2 = df2[common_cols].astype(str).agg("|".join, axis=1)

# hapus dari df2 yang ada di subsetA
df2_clean = df2[~key2.isin(set(keyA))].reset_index(drop=True)

print("df2 sebelum:", df2.shape)
print("df2 sesudah:", df2_clean.shape)

df2_clean.to_csv("Datasets/AsphaltPavementType_TEST_New.csv")

df2 sebelum: (1056, 2372)
df2 sesudah: (793, 2372)

In [3]:
df = pd.read_csv("Datasets/AsphaltPavementType_combine.csv")
df2 = pd.read_csv("Datasets/AsphaltPavementType_TEST.csv")
df3 = pd.read_csv("Datasets/AsphaltPavementType_TRAIN.csv")

df2

,TimeSeriesData_0,TimeSeriesData_1,TimeSeriesData_2,TimeSeriesData_3,TimeSeriesData_4,TimeSeriesData_5,TimeSeriesData_6,TimeSeriesData_7,TimeSeriesData_8,TimeSeriesData_9,...,TimeSeriesData_2362,TimeSeriesData_2363,TimeSeriesData_2364,TimeSeriesData_2365,TimeSeriesData_2366,TimeSeriesData_2367,TimeSeriesData_2368,TimeSeriesData_2369,TimeSeriesData_2370,ClassLabel
0,-1.618121,-2.439362,-2.740458,1.258389,1.887919,0.356795,1.999290,-0.574917,2.504297,-2.352514,...,0.300785,0.157606,0.191522,0.273604,0.158578,0.336273,0.217145,0.329172,0.282244,cobblestone
1,-5.494497,-6.046774,1.211998,-1.178592,5.093573,10.549898,1.446400,-0.230857,2.826210,-5.870671,...,0.328661,0.367679,0.241930,0.295577,0.293891,0.244364,0.370598,0.299758,0.331428,cobblestone
2,3.923206,0.478527,-0.910504,-4.133358,2.091750,1.317773,-1.554404,0.711872,1.746003,-2.813721,...,0.163358,-0.012954,0.045962,0.075396,0.116013,0.043742,-0.047875,0.041272,-0.068316,cobblestone
3,3.770494,-2.282660,-0.752969,1.458477,-1.541162,1.011944,0.344191,-3.484487,-0.740783,3.284640,...,-0.223805,-0.099245,-0.064583,-0.112051,-0.070742,-0.046163,-0.179388,-0.213290,-0.105239,cobblestone
4,0.245077,-5.182841,0.561264,1.466408,4.181481,3.170211,-6.049459,3.216879,-1.934037,-2.945427,...,-0.052628,-0.158565,-0.136236,0.001957,-0.094562,-0.099805,-0.017017,-0.081400,-0.149724,cobblestone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,-2.048245,-0.431831,2.474261,0.266421,1.045925,0.164271,-2.999506,0.258949,-0.702161,-0.750322,...,0.148767,0.206447,0.130811,0.125360,0.203498,0.182986,0.219418,0.204938,0.183945,flexible
1052,-0.482811,0.523847,-0.236167,0.147113,-0.674220,0.614470,-1.024361,0.102702,-1.408675,-0.332305,...,-0.005897,-0.016922,0.005971,-0.021707,-0.021680,0.008163,-0.009702,0.037967,0.020210,flexible
1053,0.945894,-0.969169,0.667210,-0.894546,0.671162,-2.595323,1.097331,1.537910,-1.384131,0.574048,...,0.030659,-0.074686,0.025148,-0.015091,-0.062391,0.023547,-0.053169,-0.021050,0.001647,flexible
1054,0.933206,0.142067,0.036524,-0.454885,-1.026741,0.561345,-1.236520,-0.391479,2.101343,-0.085962,...,-0.094538,-0.094186,-0.096769,-0.085870,-0.108759,-0.098714,-0.105612,-0.081816,-0.074666,flexible
1055,-1.307677,-0.734717,-2.332876,1.373376,0.324236,0.483244,2.256299,-0.054068,0.546228,0.480490,...,0.613834,0.555767,0.438718,0.509493,0.522580,0.510006,0.441031,0.455228,0.514592,flexible

In [4]:
df = pd.read_csv("Datasets/AsphaltPavementType_combine.csv")
df2 = pd.read_csv("Datasets/AsphaltPavementType_TEST.csv")
subsetA = df.iloc[1055:] 
subsetA

,TimeSeriesData_0,TimeSeriesData_1,TimeSeriesData_2,TimeSeriesData_3,TimeSeriesData_4,TimeSeriesData_5,TimeSeriesData_6,TimeSeriesData_7,TimeSeriesData_8,TimeSeriesData_9,...,TimeSeriesData_2362,TimeSeriesData_2363,TimeSeriesData_2364,TimeSeriesData_2365,TimeSeriesData_2366,TimeSeriesData_2367,TimeSeriesData_2368,TimeSeriesData_2369,TimeSeriesData_2370,ClassLabel
1055,0.695169,4.413033,0.801316,-1.594353,3.774102,-0.416691,-2.317714,-0.764167,3.978269,4.134941,...,0.132256,0.172859,0.090545,0.104179,0.067269,0.145871,-0.004069,0.141806,0.027701,cobblestone
1056,-0.369525,0.460361,-1.407053,0.541354,-1.919873,0.424794,-0.478214,0.730925,-0.993082,-0.974791,...,-0.099316,-0.131259,-0.141640,-0.137056,-0.097847,-0.134538,-0.110699,-0.100887,-0.099663,flexible
1057,-1.132577,0.845967,2.012966,1.618231,1.478052,-0.163741,1.329107,-1.361590,0.700101,-0.591235,...,0.135836,0.129473,0.159375,0.127468,0.151246,0.145376,0.188522,0.140605,0.194974,flexible
1058,-0.290975,-1.275493,-0.283407,-0.144758,-0.031406,1.372857,0.305763,0.201567,-0.439546,-0.381645,...,-0.101931,-0.090004,-0.099803,-0.067768,-0.095819,-0.112275,-0.092421,-0.098135,-0.079761,flexible
1059,0.053092,-5.684296,-3.320601,2.295371,2.097410,0.458505,2.529794,4.786021,-2.108084,-3.846709,...,0.105553,0.002282,0.029588,0.186806,0.015965,0.120522,0.045453,0.162941,0.118280,cobblestone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1314,0.880715,-2.346590,-2.329858,2.212091,-1.166301,0.371006,1.442045,-0.190440,-0.507736,-0.681386,...,-0.006118,-0.051817,-0.063536,-0.083512,-0.070412,-0.032090,-0.011215,-0.103924,0.003740,dirt
1315,-0.725810,0.307290,-0.665848,0.014449,0.020445,-0.815619,-0.315867,0.660846,-0.794393,0.261320,...,-0.030569,-0.018032,-0.018122,0.009309,-0.002325,-0.004623,-0.030401,-0.018509,0.006401,flexible
1316,6.432972,-0.184155,-4.374001,-0.011607,-1.068614,4.028121,2.998381,-3.004130,2.899988,-0.824554,...,-0.036395,-0.132641,-0.009433,-0.154533,-0.064270,-0.051793,-0.099983,-0.039613,-0.086337,cobblestone
1317,-0.416838,2.559118,-1.690034,-0.278789,0.573216,0.116075,-0.407203,1.595101,-4.097763,1.875713,...,-0.007052,-0.006644,-0.037258,-0.027634,-0.019115,0.009543,-0.076739,0.016153,0.008333,dirt
1318,-0.711354,-3.268203,-0.820679,1.116180,-2.884878,-0.813056,-1.659677,-2.995004,1.513465,0.041381,...,0.189315,0.251214,0.290267,0.282521,0.236136,0.278041,0.198825,0.206936,0.298122,dirt

In [5]:
subsetA = df.iloc[1055:]  # baris 10-12
gabung = subsetA.merge(df2.drop_duplicates(), how="inner")

cols = df.columns.tolist()
match_idx = subsetA.merge(df2.drop_duplicates(), how="inner", on=cols).index

setB = set(map(tuple, df2[cols].to_numpy()))
mask_match = df.iloc[1055:][cols].apply(tuple, axis=1).isin(setB)

dfA_baru = df.drop(df.index[1055:][mask_match])
dfA_baru

# # ambil semua baris di dfB yang sama persis dengan subsetA
# gabung = subsetA.merge(dfB.drop_duplicates(), how="inner")

# # index subsetA yang cocok (pakai merge berdasarkan semua kolom)
# cols = dfA.columns.tolist()
# match_idx = subsetA.merge(dfB.drop_duplicates(), how="inner", on=cols).index  # ini index merge, bukan dfA

# # cara aman: buat mask pakai tuple row
# setB = set(map(tuple, dfB[cols].to_numpy()))
# mask_match = dfA.iloc[10:13][cols].apply(tuple, axis=1).isin(setB)

# dfA_baru = dfA.drop(dfA.index[10:13][mask_match])

KeyboardInterrupt:

In [23]:
df2 = pd.read_csv("Datasets/AsphaltPavementType_TEST.csv")
df2_new = df2.drop(columns=['ClassLabel'])
df_neww = df2_new.iloc[:30]
df_neww.to_csv("Data_test_new.csv") 
df_neww

# df2.iloc[:12]

,TimeSeriesData_0,TimeSeriesData_1,TimeSeriesData_2,TimeSeriesData_3,TimeSeriesData_4,TimeSeriesData_5,TimeSeriesData_6,TimeSeriesData_7,TimeSeriesData_8,TimeSeriesData_9,...,TimeSeriesData_2361,TimeSeriesData_2362,TimeSeriesData_2363,TimeSeriesData_2364,TimeSeriesData_2365,TimeSeriesData_2366,TimeSeriesData_2367,TimeSeriesData_2368,TimeSeriesData_2369,TimeSeriesData_2370
0,-1.618121,-2.439362,-2.740458,1.258389,1.887919,0.356795,1.999290,-0.574917,2.504297,-2.352514,...,0.228019,0.300785,0.157606,0.191522,0.273604,0.158578,0.336273,0.217145,0.329172,0.282244
1,-5.494497,-6.046774,1.211998,-1.178592,5.093573,10.549898,1.446400,-0.230857,2.826210,-5.870671,...,0.227066,0.328661,0.367679,0.241930,0.295577,0.293891,0.244364,0.370598,0.299758,0.331428
2,3.923206,0.478527,-0.910504,-4.133358,2.091750,1.317773,-1.554404,0.711872,1.746003,-2.813721,...,0.154495,0.163358,-0.012954,0.045962,0.075396,0.116013,0.043742,-0.047875,0.041272,-0.068316
3,3.770494,-2.282660,-0.752969,1.458477,-1.541162,1.011944,0.344191,-3.484487,-0.740783,3.284640,...,-0.067687,-0.223805,-0.099245,-0.064583,-0.112051,-0.070742,-0.046163,-0.179388,-0.213290,-0.105239
4,0.245077,-5.182841,0.561264,1.466408,4.181481,3.170211,-6.049459,3.216879,-1.934037,-2.945427,...,-0.166311,-0.052628,-0.158565,-0.136236,0.001957,-0.094562,-0.099805,-0.017017,-0.081400,-0.149724
5,2.435869,-0.453992,2.613757,0.639988,-3.618456,1.773713,-2.733408,-4.935425,3.054903,-3.645966,...,-0.129813,-0.162974,-0.149661,-0.178046,-0.224263,-0.166863,-0.245799,-0.251785,-0.212977,-0.222057
6,-4.786182,-2.565554,1.216936,4.578896,-0.571731,2.608341,-1.167742,-0.751043,-3.391470,-6.774874,...,-0.191895,-0.212134,-0.127998,-0.132975,-0.187808,-0.073680,-0.081350,-0.151255,-0.167610,-0.111455
7,-0.079734,-1.698306,-2.050573,1.628708,0.321700,-1.988773,7.285965,0.467096,-2.888209,-3.347199,...,-0.085456,0.122688,0.032831,0.080279,0.059682,-0.016297,-0.082128,-0.024357,-0.010924,0.003095
8,-0.683771,3.345447,-2.046179,-1.904928,1.922493,3.244203,-2.809296,3.394939,1.180828,-2.265437,...,-0.107925,-0.190442,-0.234597,-0.125230,-0.140433,-0.149352,-0.174903,-0.253484,-0.210242,-0.154932
9,-1.943987,5.456226,-1.724751,-1.378545,1.967652,-4.518701,4.765369,4.158512,-1.040733,-0.083979,...,-0.016831,0.129125,-0.001158,-0.018450,0.022978,0.094294,0.149588,0.129826,0.092161,-0.038523
10,1.823590,0.055485,-1.877778,6.806085,-0.158225,-8.541594,0.716441,-3.442936,1.151114,11.548522,...,-0.089166,-0.124397,-0.148376,-0.046884,-0.202885,-0.173987,-0.211348,-0.088997,-0.107523,-0.156652
11,-1.894011,6.933532,3.229123,-0.252562,-0.947504,-1.613200,-2.420474,2.509079,3.894519,-0.173369,...,-0.262578,-0.180035,-0.288420,-0.170021,-0.215318,-0.187274,-0.242788,-0.228292,-0.197377,-0.160045
12,-4.377089,-0.637276,0.271067,-4.089209,-2.697450,-1.405307,-2.329681,-2.098256,-0.692053,0.719198,...,-0.067530,-0.219560,-0.148699,-0.074615,-0.066178,-0.021795,-0.107857,-0.032660,-0.062911,-0.030363
13,-2.173108,1.338908,-1.711524,-1.661275,0.869891,-1.083742,-4.439667,-0.696213,2.181504,-1.511370,...,-0.038262,-0.090168,-0.048874,-0.092673,-0.018466,-0.002325,-0.009078,-0.058539,-0.003399,-0.129084
14,0.266712,-1.339174,-3.530905,0.798931,4.542467,-1.107614,-2.902818,0.958427,-1.091226,-2.079743,...,0.023430,0.143998,0.126352,0.072554,-0.019627,0.082795,-0.034077,0.127994,0.090587,0.108556
15,0.542485,-1.276479,2.226426,-2.199670,-4.160748,10.372925,-8.030281,-3.656679,10.128040,-5.211294,...,-0.042346,-0.177502,-0.159505,-0.099050,-0.128049,-0.019815,-0.107999,-0.033594,-0.178782,-0.080573
16,0.010872,-7.548143,-6.914458,6.635066,5.879062,-1.093391,3.699303,1.002709,-4.802033,-3.572100,...,0.165602,0.281658,0.199236,0.275290,0.204913,0.110889,0.243981,0.270935,0.173377,0.292184
17,0.607566,-0.062241,3.098335,-0.877538,-0.751807,1.524690,-0.049329,2.044838,0.896648,-1.124885,...,-0.197078,-0.152833,-0.158881,-0.115426,-0.096196,-0.202564,-0.174549,-0.132328,-0.119251,-0.178951
18,-5.004574,0.715188,4.774008,-0.317997,2.134360,-1.431318,-1.036147,-1.686238,0.204561,-2.138260,...,0.113523,0.150317,0.163914,0.183565,0.095206,0.204912,0.161681,0.201223,0.187875,0.080298
19,-7.539162,9.178038,1.643815,-2.664229,2.103120,-0.046783,-3.812926,3.146635,2.856872,-3.959188,...,0.117534,0.009013,0.136549,-0.072435,0.117975,0.040539,0.074275,0.099239,0.133089,-0.074544
20,6.305859,1.558306,-2.138963,1.652534,-0.127602,0.537659,2.592212,0.103629,3.685535,0.617663,...,-0.048378,-0.026882,-0.105151,0.064115,-0.034047,0.014127,-0.113988,-0.002746,0.032278,-0.052424
21,1.995350,-2.493230,1.916243,2.916442,-0.245054,0.867404,1.823552,3.644653,-2.119445,-2.914951,...,0.039439,0.043692,0.181936,0.089718,0.140368,0.188385,0.181157,0.195027,0.155906,0.205703
22,3.881489,0.682023,-1.343815,-1.108883,-1.735018,-3.875592,0.371245,-0.477532,-0.732838,-2.359653,...,0.014712,0.033879,0.105461,0.082844,-0.025150,-0.052390,0.057843,0.013062,0.005154,0.091962
23,-1.125873,-2.103697,2.228091,-4.486758,0.423271,-2.799184,0.370092,2.098388,-5.947223,-0.377049,...,-0.060026,-0.112940,-0.139341,-0.153862,-0.054899,-0.006251,-0.039748,-0.143998,-0.108720,-0.105831
24,1.498883,-1.020833,2.484382,2.955167,-1.779095,-1.329749,-1.191310,-1.076296,2.901557,-2.202463,...,-0.089979,-0.199234,-0.102355,-0.103301,-0.148800,-0.180457,-0.190417,-0.139501,-0.128636,-0.103736
25,-1.887564,-2.660852,-5.812025,0.037935,1.158780,0.101169,-1.704588,-0.024104,3.348553,-3.431099,...,-0.110958,-0.105728,-0.116840,-0.144608,-0.087240,-0.068043,-0.120449,-0.159877,-0.119208,-0.050861
26,0.143862,2.633169,3.766631,2.842819,0.826558,2.105702,5.033502,0.076932,-3.206989,-2.370383,...,0.003755,-0.006411,-0.002030,-0.113635,-0.144883,-0.110578,-0.145598,-0.145380,-0.105127,-0.037965
27,-0.557758,-1.503015,-3.528168,-0.873179,3.987526,-2.599367,0.462944,-0.287791,4.552304,-0.137106,...,-0.172813,-0.150821,-0.137707,-0.135187,-0.280857,-0.284856,-0.283506,-0.290634,-0.174998,-0.289825
28,3.888654,-2.748218,-3.048559,-1.094455,3.334965,-0.351652,-3.818124,-0.125497,1.405876,-1.582442,...,-0.201242,-0.253935,-0.344762,-0.250268,-0.269478,-0.192206,-0.276941,-0.329514,-0.312212,-0.264596
29,-0.706473,-1.066381,0.399479,2.093951,5.056561,1.355641,1.785450,0.868251,-6.420739,0.830549,...,0.123972,0.243894,0.310486,0.133101,0.188706,0.130795,0.263925,0.136637,0.314655,0.301464